### ISSUE TITLE
Asynchronous operations missed

### ISSUE THREAD

**Issue by Shiko1st** [e1em3ntoDX/AzureCosmosDBReportStorage#1]
https://github.com/e1em3ntoDX/AzureCosmosDBReportStorage/blob/4765b09bf648604705469fb5b93a51925f7fde43/DXCosmosExample/ReportStorageWebExtension.cs#L79

It is a kidding?
Why reporting engine doesn't support asynchronous operations in the end of 2020?

**Comment by e1em3ntoDX** [comment]
Closed as a duplicate to [Asynchronous operations are missed](https://github.com/e1em3ntoDX/AzureCosmosDBReportStorage/issues/2)
