### ISSUE TITLE
Asynchronous operations are missed

### ISSUE THREAD

**Issue by Shiko1st** [e1em3ntoDX/AzureCosmosDBReportStorage#2]
https://github.com/e1em3ntoDX/AzureCosmosDBReportStorage/blob/4765b09bf648604705469fb5b93a51925f7fde43/DXCosmosExample/ReportStorageWebExtension.cs#L79

It is a kidding?
Why reporting engine doesn't support asynchronous operations at the end of 2020?

**Comment by e1em3ntoDX** [comment]
Hi @Shiko1st,

I believe that this is one of the new features we're going to roll out as a part of our next major update - v20.2. See the **Web Reporting - Async Report Storage** section from the following blog post: [Reporting — Early Access Preview (v20.2)](https://community.devexpress.com/blogs/reporting/archive/2020/08/24/reporting-early-access-preview-v20-2.aspx). You can also refer to the sample that demonstrates the implementation: [How to Use the Asynchronous Engine for Web Reporting](https://github.com/DevExpress-Examples/Reporting-Use-Async-Engine-In-AspNet-Core).

Let us know if this helps. 

Regards,
Dmitry

**Comment by Shiko1st** [comment]
Hi @e1em3ntoDX,
it seems I've missed that. Can't wait for 20.2 be released!

**Comment by e1em3ntoDX** [comment]
Thank you for the update. I'm happy to hear that the information I shared is helpful.

The release of v20.2 is just around the corner. Watch our website for updates!
